### ISSUE TITLE
Install fails with Guzzle 7.0.1 installed

### ISSUE THREAD

**Issue by weavdale** [tightenco/takeout#62] opened 2020-08-26 19:47 UTC
~ composer global require tightenco/takeout

Changed current directory to /Users/dalew/.composer
Using version ^1.0 for tightenco/takeout
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for tightenco/takeout ^1.0 -> satisfiable by tightenco/takeout[v1.0.0].
    - Conclusion: remove guzzlehttp/guzzle 7.0.1
    - Conclusion: don't install guzzlehttp/guzzle 7.0.1
    - tightenco/takeout v1.0.0 requires guzzlehttp/guzzle ^6.5 -> satisfiable by guzzlehttp/guzzle[6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5].
    - Can only install one of: guzzlehttp/guzzle[6.5.0, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.1, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.2, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.3, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.4, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.5, 7.0.1].
    - Installation request for guzzlehttp/guzzle (locked at 7.0.1) -> satisfiable by guzzlehttp/guzzle[7.0.1].

**Comment by sheldonkotyk** [comment] 2020-08-26 19:50
All I have is valet and the Laravel installer globally.

**Comment by mattstauffer** [comment] 2020-08-26 19:58
Please update your global dependencies and then try again. Also will soon be addressed by #64.

**Comment by filipac** [comment] 2020-08-26 20:04
@mattstauffer updated all global dependencies but still nope :) all i have locally installed, latest versions for all:
```
"require": {
    "laravel/valet": "^2.10",
    "spatie/phpunit-watcher": "^1.22",
    "laravel/installer": "^3.2",
    "beyondcode/expose": "^1.3"
  }
```

**Comment by OliverTe** [comment] 2020-08-26 20:06
Same here. Issue is: 
- tightenco/takeout v1.0.0 requires guzzlehttp/guzzle ^6.5 -> satisfiable by guzzlehttp/guzzle[6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5].

Have 7.0.1 installed, but ^6.5 is not satisfied with 7.0.1

**Comment by filipac** [comment] 2020-08-26 20:30
Opened #67 and this should make it work with any other globally installed package.

**Comment by jonsugar** [comment] 2020-08-26 20:33
The issue is caused if the Laravel installer (or another package that requires it) is installed before Takeout. The Laravel installer requires guzzle ^6.0|^7.0 and installs 7.0 if it can. If Takeout is installed first then Guzzle 6.5 will be installed and the Laravel installer will just use that.

For now, you can remove the Laravel installer install Takeout then re-install the Laravel installer.

A hack I know but it should work until Takeout is fixed.

**Closed** 2020-08-27 01:20 UTC
